### ISSUE TITLE
membuat method create

### ISSUE THREAD

**Issue by faridwidhy** [faridwidhy/P11_service#7]

**Comment by aliefezaa** [comment]
else if($_SERVER['REQUEST_METHOD'] === 'POST'){
    $judul_buku = $_POST['judul_buku'];
    $jumlah = $_POST['jumlah'];
    $harga = $_POST['harga'];
    $sql = "INSERT INTO stok_buku (judul_buku, jumlah, harga) VALUES ('$judul_buku','$jumlah','$harga')";
    $cek = mysqli_query($koneksi, $sql);

    $response = ['status' => $cek ? 'berhasil' : 'gagal'];
    echo json_encode($response);
}
